### ISSUE TITLE
appear to be constant with groups

### ISSUE THREAD

**Issue by celinechen1885** [waldronlab/lefser#32]
Hi!

I'm working with a shotgun metagenomics data, and we aim to analyze the functional profile. 
we have 224 samples in total, with 356 different pathways.
below are the codes that I used
metagenomic_lefse <- read.csv
se <- SummarizedExperiment(assays = list(counts = as.matrix(metagenomic_lefse)))
colData(se) <- DataFrame(metadata)
se$group <- as.factor(se$group)
se$DI <- as.factor(se$DI)
se_relab <- relativeAb(se)
> res <- lefser(se_relab, groupCol = "group")

I got an error message:
Error in lda.default(x, grouping, ...) : 
  variables  85 145 appear to be constant within groups

Could anyone help me with it?
Thanks!

**Comment by Peacesandy** [comment]
Okay, I'll make a pull request as soon as I'm done

**Comment by Peacesandy** [comment]
I just made a pull request 
@lwaldron 

https://github.com/waldronlab/lefser/pull/34

**Comment by lwaldron** [comment]
Fixed by 8864568581444d1dfbcb12f8ef3348e19968ea08 (v1.13.2) and this error no longer appears. Thank you for the report, @celinechen1885 . @asyakhl will you push to bioc-devel ASAP?  @celinechen1885, the easiest way to access this fix for now is to install from GitHub (`BiocManager::install("waldronlab/lefser")`), or just multiply your relative abundance values by 1e6.

**Comment by lwaldron** [comment]
@asyakhl **please** push to bioc-devel and cherry-pick to bioc-release. This is an important bugfix.

**Comment by LiNk-NY** [comment]
@lwaldron I've updated both. Thanks!

**Comment by lwaldron** [comment]
Thanks Marcel!
